name: Provision and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy Infrastructure and Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0  # Use a specific version for consistency
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      # Removing the terraform_version will default to the latest version of Terraform
      # with:
      #   terraform_version: latest

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Get K8s Credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.GCP_REGION }} --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy Application
      run: |
        kubectl apply -f k8s/nginx-deployment.yaml
        kubectl apply -f k8s/nginx-service.yaml
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        GCP_REGION: ${{ secrets.GCP_REGION }}
